### ISSUE TITLE
merge pkg/config with pkg/driver

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/lvm-localpv#8] opened 2021-01-05 10:32 UTC
**Describe the problem/challenge you have**

Merge pkg/config into pkg/driver as the config is driver specific.

**Comment by OussamaSALAHOUELHADJ** [comment] 2021-10-03 10:42
Hey @pawanpraka1, just to clarify, by merging do you mean moving files from pkg/config to pkg/driver and then deleting pkg/config?

**Comment by pawanpraka1** [comment] 2021-10-03 11:45
@OussamaSALAHOUELHADJ yes, that is correct. And also we need to fix the references in code to point to the new location.

**Comment by OussamaSALAHOUELHADJ** [comment] 2021-10-03 11:50
ok Got it, can you please assign it to me.

**Comment by OussamaSALAHOUELHADJ** [comment] 2021-10-04 06:02
Hey @pawanpraka1, I am in the process of merging pkg/config into pkg/driver, while fixing the references in the code I got this compiling error:
```
import cycle not allowed: import stack: [github.com/openebs/lvm-localpv/cmd github.com/openebs/lvm-localpv/pkg/driver github.com/openebs/lvm-localpv/pkg/collector github.com/openebs/lvm-localpv/pkg/lvm github.com/openebs/lvm-localpv/pkg/driver]
```
the problem is that `lvm` package imports the `config` package and the `driver` package imports the `lvm` package causing the import cycle...
instead of moving files from `config` to `driver`, I suggest including the `driver` package inside `driver`, so the path will be: `...pkg/driver/config`
Do you have any suggestions?

**Comment by pawanpraka1** [comment] 2021-10-04 06:13
Moving to pkg/driver/config sounds good to me.

**Comment by OussamaSALAHOUELHADJ** [comment] 2021-10-04 08:18
A PR has been submitted regarding this issue, please review. #160

**Closed** 2021-10-05 15:05 UTC
Labels: help wanted, good first issue
