### ISSUE TITLE
add support of lvm-localpv to run in other distros of linux

### ISSUE THREAD

**Issue by mittachaitu** [openebs/lvm-localpv#75] opened 2021-05-21 09:07 UTC
**Describe the problem/challenge you have**
Used RHEL **centos-7** to provision volumes, when I deployed the
application pod it stuck in `ContainerCreating` state due to mounting issues.
```sh
 Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs -o defaults /dev/lvmvg/pvc-a77bc831-76ec-40b1-80ed-8cdcaa7187d1 /var/lib/kubelet/pods/bcb76f32-d9ce-48b5-b255-dfa31147f5a6/volumes/kubernetes.io~csi/pvc-a77bc831-76ec-40b1-80ed-8cdcaa7187d1/mount
Output: mount: /var/lib/kubelet/pods/bcb76f32-d9ce-48b5-b255-dfa31147f5a6/volumes/kubernetes.io~csi/pvc-a77bc831-76ec-40b1-80ed-8cdcaa7187d1/mount: wrong fs type, bad option, bad superblock on /dev/mapper/lvmvg-pvc--a77bc831--76ec--40b1--80ed--8cdcaa7187d1, missing codepage or helper program, or other error.
```

**Describe the solution you'd like:**
It is good to add support of lvm-local PV on different linux distros.

**Anything else you would like to add:**
No

**Environment:**
- LVM Driver version: lvm2
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by huzhengchuan** [comment] 2021-06-11 05:52
[root@hzcmaster0 openebs-example]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"

meet the same question！

**Comment by mpepping** [comment] 2021-07-29 09:34
Using EL8 (Centos 8) there is no issue whatsoever in using lvm-localpv. The deployment is straightforward. The PVC/PV lifecycle works as expected, and LVM logical-volume devices are created/mounted/removed as supposed. All good!

Now, the [README.md](https://github.com/openebs/lvm-localpv/blob/master/README.md#L38) limits the supported system config to Ubuntu. Will CentOS 8 / RHEL 8 be considered as a supported target platform?

**Comment by mittachaitu** [comment] 2021-09-13 05:39
After digging into the issue found the root cause of not being able to mount xfs formatted LVM volumes...  It was happening due to incompatibility between xfs version inside the csi-container and xfs version at host machine... To address this issue we have to format the xfs with following option `mkfs.xfs -m reflink=0 <device_name>`

**Comment by davidkarlsen** [comment] 2021-09-19 22:18
This is a duplicate of #135. It's because mount_utils doesn't force format xfs filesystems.

**Comment by dsharma-dc** [comment] 2024-06-04 05:13
Closing this one as there are three issues open already for same problem, mentioned in previous comments.

**Closed by dsharma-dc** 2024-06-04 05:13 UTC
