### ISSUE TITLE
Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock

### ISSUE THREAD

**Issue by YangLoveYing** [openebs/lvm-localpv#217] opened 2022-12-13 08:38 UTC
the openebs-lvm-controller is running, but when I see the log of this pod. It always reminds me "still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock. I occured this issue in physical machine, virtual machine doesn't occur. could you help me, thanks

**Comment by Abhinandan-Purkait** [comment] 2023-09-07 08:21
Hey @YangLoveYing Can you please share the the environment, machine, details. Also can you share the steps that led you into this?

**Comment by YangLoveYing** [comment] 2023-09-07 08:22
邮件我已收到，谢谢

**Comment by dsharma-dc** [comment] 2024-06-05 10:46
@YangLoveYing Please provide the details requested earlier in case you still have this issue. In case it is resolved, please confirm.

**Comment by YangLoveYing** [comment] 2024-06-05 10:47
邮件我已收到，谢谢

**Comment by avishnu** [comment] 2024-09-19 10:10
@YangLoveYing unable to reproduce the issue. Please check with the latest release. Closing this for now. If it persists, you can re-open, but you need to provide the details as suggested by @dsharma-dc and @Abhinandan-Purkait .

**Comment by YangLoveYing** [comment] 2024-09-19 10:11
邮件我已收到，谢谢

**Closed as completed by avishnu** 2024-09-19 10:10 UTC
Labels: kind/support
